name: "example"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout this project (including ./scripts dir)
      - name: Script Kit
        uses: johnlindquist/kit-action@main
        with:
          script: "./scripts/example-script.js" # The name of a script in your ./scripts dir
